instance_name = "default"
instance_id = "f9f05421-7c6b-47d6-a67d-4d58d49f51d8"
dhcp = true
listeners = []
exit_nodes = []
rpc_portal = "0.0.0.0:15888"

[network_identity]
network_name = "my_server"
network_secret = "7#kQ$9zP!mN2@xL*"

[[peer]]
uri = "tcp://180.184.65.184:11010"

[file_logger]
level = "info"
file = "easytier-default"
dir = "/tmp"
